### ISSUE TITLE
[feature] assign Gio.DBusConnectionFlags for Gio.DBusConnection.new_for_address_sync

### ISSUE THREAD

**Issue by Freed-Wu** [stefano-m/lua-dbus_proxy#14]
Comes from #13 

https://github.com/stefano-m/lua-dbus_proxy/blob/master/src/dbus_proxy/_bus.lua#L34 pass None to Connection Flags.
Can we allow to assign flags?

TIA!

**Comment by stefano-m** [comment]
Hi, it would be great if you could add more details as I asked in https://github.com/stefano-m/lua-dbus_proxy/issues/13#issuecomment-2308374086

**Comment by stefano-m** [comment]
Fixed by 2c4c1009536d607765122e9c9a432f6d8fae36e6
